version: '3'

services:
  liststd:
    build: ./liststd
    volumes:
      - /opt/liststd:/usr/src/app
    ports:
      - 5000:80

  website:
    image: centos:7 
    container_name: mrami
    volumes:
      - /opt/website:/var/www/html
    ports:
      - 3000:80
    depends_on:
      - liststd
